version: "3.9"
services:
  validator-1:
    image: ashlesh/polygon-sdk
    working_dir: /root
    entrypoint: ""
    command: "polygon server --data-dir /root/chain --chain /root/genesis.json --grpc validator-1:2000 --libp2p validator-1:1478 --jsonrpc validator-1:8545 --seal"
    volumes:
      - ./genesis.json:/root/genesis.json
      - ./data-dir-1:/root/chain
    ports:
      - 8545:8545

  validator-2:
    image: ashlesh/polygon-sdk
    working_dir: /root
    entrypoint: ""
    command: "polygon server --data-dir /root/chain --chain /root/genesis.json --grpc validator-2:2000 --libp2p validator-2:1478 --jsonrpc validator-2:8545 --seal"
    volumes:
      - ./genesis.json:/root/genesis.json
      - ./data-dir-2:/root/chain

  validator-3:
    image: ashlesh/polygon-sdk
    working_dir: /root
    entrypoint: ""
    command: "polygon server --data-dir /root/chain --chain /root/genesis.json --grpc validator-3:2000 --libp2p validator-3:1478 --jsonrpc validator-3:8545 --seal"
    volumes:
      - ./genesis.json:/root/genesis.json
      - ./data-dir-3:/root/chain

  validator-4:
    image: ashlesh/polygon-sdk
    working_dir: /root
    entrypoint: ""
    command: "polygon server --data-dir /root/chain --chain /root/genesis.json --grpc validator-4:2000 --libp2p validator-4:1478 --jsonrpc validator-4:8545 --seal"
    volumes:
      - ./genesis.json:/root/genesis.json
      - ./data-dir-4:/root/chain

networks:
  default:
    name: polygon-network
