version: "3.9"
services:
  validator-1:
    image: 0xpolygon/polygon-edge:0.2.0
    working_dir: /root
    entrypoint: ""
    command: "polygon-edge server --price-limit 0 --data-dir /root/chain --chain /root/genesis.json --grpc validator-1:2000 --libp2p validator-1:1478 --jsonrpc validator-1:8545 --seal"
    volumes:
      - ./genesis.json:/root/genesis.json
      - ./data-dir-1:/root/chain
    ports:
      - 8545:8545

networks:
  default:
    name: polygon-network
